### ISSUE TITLE
[DOCUMENTATION] should include information that the backend user needs at least "dummy" group assigned

### ISSUE THREAD

**Issue by AndreasA** [georgringer/be_acl_file#3]
Because this EXT uses 
$GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['t3lib/class.t3lib_userauthgroup.php']['fetchGroups_postProcessing'] 
Hook which is in fetchGroups() of BackendUserAuthentication.
However, that method is only called if a user has groups. So each user needs to at least have a dummy group set.
Corresponding check in BackendUserAuthentication:
```
$grList = $this->db->cleanIntList($this->user[$this->usergroup_column]);
if ($grList) {
	// Fetch groups will add a lot of information to the internal arrays: modules, accesslists, TSconfig etc.
	// Refer to fetchGroups() function.
	$this->fetchGroups($grList);
}
```

**Comment by georgringer** [comment]
thx!
